<?php

namespace MeloLab\BioGestion\FileUploadBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * This is the class that validates and merges configuration from your app/config files
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/extension.html#cookbook-bundles-extension-config-class}
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('melolab_biogestion_fileupload');

        // Here you should define the parameters that are allowed to
        // configure your bundle. See the documentation linked above for
        // more information on that topic.
        
        $rootNode
            ->children()
                ->scalarNode('max_file_size')
                    ->defaultValue('5M')
                    ->info('Max file size (global setting), e.g. 5M or 500K')
                ->end()
                ->scalarNode('accepted_file_types')
                    ->defaultValue('/(\.|\/)(pdf)$/i')
                    ->info('Acceptable file extensions regular expression (global seeting), e.g. /(\.|\/)(pdf)$/i')
                ->end()
                ->scalarNode('temp_files_path')
                    ->info('Temporary files storage folder')
                ->end()
                ->arrayNode('mappings')
                    ->useAttributeAsKey('id')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('entity')
                                ->isRequired()
                                ->cannotBeEmpty()
                                ->info('Fully qualified entity class name')
                            ->end()
                            ->scalarNode('file_field')
//                                ->isRequired()
//                                ->cannotBeEmpty()
                                ->info('File field (variable name). A default value is generated by camel-casing the '
                                        . 'key of this configuration entry, e.g. if the configuration key is "profile_picture" '
                                        . 'the file_field will be "profilePicture"')
                            ->end()
                            ->scalarNode('file_getter')
//                                ->isRequired()
//                                ->cannotBeEmpty()
                                ->info('Getter of the file variable. Defaults to "get<file_field>", where <file_field> '
                                        . 'is the capitalized configuration value, e.g. "getProfilePicture"')
                            ->end()
                            ->scalarNode('file_setter')
//                                ->isRequired()
//                                ->cannotBeEmpty()
                                ->info('Setter of the file variable. Defaults to "set<file_field>", where <file_field> '
                                        . 'is the capitalized configuration value, e.g. "setProfilePicture"')
                            ->end()
                            ->scalarNode('filename_getter')
//                                ->isRequired()
//                                ->cannotBeEmpty()
                                ->info('Getter of the filename variable. Defaults to "get<file_field>Name", where '
                                        . '<file_field> is the capitalized configuration value, e.g. "getProfilePictureName"')
                            ->end()
                            ->scalarNode('filename_setter')
//                                ->isRequired()
//                                ->cannotBeEmpty()
                                ->info('Setter of the filename variable. Defaults to "set<file_field>Name", where '
                                        . '<file_field> is the capitalized configuration value, e.g. "getProfilePictureName"')
                            ->end()
                            ->scalarNode('vich_mapping')
//                                ->isRequired()
//                                ->cannotBeEmpty()
                                ->info('Vich Uploader mapping. Defaults to key of this configuration entry, e.g. '
                                        . '"profile_picture"')
                            ->end()
                            ->scalarNode('max_file_size')
                                ->info('Max file size in MB, overrides the global setting')
                            ->end()
                            ->scalarNode('accepted_file_types')
                                ->info('Acceptable file extensions regular expression, overrides the global setting')
                            ->end()
                            ->scalarNode('repository_method')
                                ->info('Repository method to find the entity')
                                ->defaultValue('findOneById')
                            ->end()
                            ->booleanNode('allow_anonymous_downloads')
                                ->info('Set true to allow access to file downloads by anonymous (not logged in) users')
                                ->defaultFalse()
                            ->end()
                            ->booleanNode('allow_anonymous_uploads')
                                ->info('Set true to allow access to file uploads by anonymous (not logged in) users')
                                ->defaultFalse()
                            ->end()
                            ->booleanNode('download_ignore_security')
                                ->info('Do not check security when downloading a file')
                                ->defaultFalse()
                            ->end()
                            ->arrayNode('download_allowed_referer_routes')
                                ->info('Allow downloads only from these referer routes. Required when download_ignore_security is enabled')
                                ->prototype('scalar')->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();
        

        return $treeBuilder;
    }
}
